name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions 😃
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -run: echo " The job was automatically triggered by a ${{ github.event_name }} event."
      -run: echo "This is an action that checks out your repository onto the runner"
      -uses: actions/checkout@v3
      -run: echo "This is action to install the specified version of the Node.js"
      -uses: actions/setup-node@v3
        with:
          node-version: '18'
      -run: echo "Installing dependencies"
      -run: npm install
      -run: echo "Set up poject"
      -run: make setup
      -run: echo "Run linter"
      -run: make lint
      -run: echo "Run test"
      -run: make test
